### Teste da rota de criação de músicos
POST http://localhost:3001/musicos
Content-Type: application/json

{
  "name": "João Silva",
  "sexo": "M",
  "aluno": true,
  "ensaios": true,
  "rjm": false,
  "cultos_oficiais": false,
  "oficializado": false,
  "possui_instrumento_proprio": true,
  "instrumento": true,
  "tonalidade": "Dó",
  "encarregado_local": true,
  "encarregado_regional": false,
  "instrutor": false,
  "examinadora": false
}

### Teste da rota de listagem de músicos
GET http://localhost:3001/musicos

### Teste da rota de criação de músico organista
POST http://localhost:3001/musicos
Content-Type: application/json

{
  "name": "Maria Santos",
  "sexo": "F",
  "aluno": false,
  "ensaios": true,
  "rjm": true,
  "cultos_oficiais": true,
  "oficializado": true,
  "possui_instrumento_proprio": true,
  "instrumento": true,
  "tonalidade": "Fá",
  "encarregado_local": false,
  "encarregado_regional": false,
  "instrutor": false,
  "examinadora": false
}

### Cadastrar Genilson Monteiro da Silva - Flautista Oficializado
POST http://localhost:3001/musicos
Content-Type: application/json

{
  "name": "Genilson Monteiro da Silva",
  "sexo": "M",
  "aluno": false,
  "ensaios": true,
  "rjm": true,
  "cultos_oficiais": true,
  "oficializado": true,
  "possui_instrumento_proprio": true,
  "instrumento": true,
  "tonalidade": "Dó",
  "encarregado_local": false,
  "encarregado_regional": false,
  "instrutor": false,
  "examinadora": false
}
